# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    exchange_service_endpoint: '%env(EXCHANGE_SERVICE_ENDPOINT)%'
    exchange_service_access_key: '%env(EXCHANGE_SERVICE_ACCESS_KEY)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ApiService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Service\ExchangeRateService:
        arguments:
            $apiService: '@App\Service\ApiService'
            $endpoint: '%exchange_service_endpoint%'
            $accessKey: '%exchange_service_access_key%'

#    App\Service\CommissionCalculator:
#        arguments:
#            $exchangeRateService: '@App\Service\ExchangeRateService'
#            $freeWithdrawalsLimit: '%env(int:WEEKLY_FREE_WITHDRAWALS_LIMIT)%'
#            $freeAmountLimit: '%env(float:WEEKLY_FREE_AMOUNT_LIMIT)%'
#            $depositFeePercentage: '%env(float:DEPOSIT_FEE_PERCENTAGE)%'
#            $privateWithdrawalFeePercentage: '%env(float:PRIVATE_WITHDRAWAL_FEE_PERCENTAGE)%'
#            $businessWithdrawalFeePercentage: '%env(float:BUSINESS_WITHDRAWAL_FEE_PERCENTAGE)%'

    App\Service\Strategy\DepositCommissionStrategy:
        arguments:
            $feePercentage: '%env(float:DEPOSIT_FEE_PERCENTAGE)%'
        tags:
            - { name: 'app.commission_strategy' }

    App\Service\Strategy\PrivateWithdrawCommissionStrategy:
        arguments:
            $exchangeRateService: '@App\Service\ExchangeRateService'
            $freeWithdrawalsLimit: '%env(int:WEEKLY_FREE_WITHDRAWALS_LIMIT)%'
            $freeAmountLimit: '%env(float:WEEKLY_FREE_AMOUNT_LIMIT)%'
            $feePercentage: '%env(float:PRIVATE_WITHDRAWAL_FEE_PERCENTAGE)%'
        tags:
            - { name: 'app.commission_strategy' }

    App\Service\Strategy\BusinessWithdrawCommissionStrategy:
        arguments:
            $feePercentage: '%env(float:BUSINESS_WITHDRAWAL_FEE_PERCENTAGE)%'
        tags:
            - { name: 'app.commission_strategy' }

    # Register the factory
    App\Service\Strategy\CommissionStrategyFactory:
        arguments:
            $strategies: !tagged_iterator app.commission_strategy

    App\Service\CommissionCalculator:
        arguments:
            $strategyFactory: '@App\Service\Strategy\CommissionStrategyFactory'
